/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define DEBUG_PRINTF 1

#include <stdint.h>
#include "main.h"
#include "ADC/ADC.h"
#include "GPIO/GPIO.h"
#include "Console/Console.h"


#define ADC_MAX       4095.0f    // 12-bit ADC
#define VREF          3.3f       // ADC reference voltage (V)
#define R_FIXED       10000.0f   // Pull-down resistor value (Ω)
#define R0            10000.0f   // Thermistor resistance at T0 (Ω)
#define B_COEF        3950.0f    // Beta coefficient (K)
#define T0_KELVIN     298.15f    // 25 °C in Kelvin

//#define NUM_CHANNELS 4
//uint16_t adc_buffer[NUM_CHANNELS];

ADC_Config thermistor_config;
volatile uint16_t thermistor_buffer[5];

const uint16_t resistor_ref = 10000;

volatile float thermistor[5] = {0};


float digital_to_analog(uint16_t digital)
{
	return(((float)digital*3.3)/4096.0);
}

float Thermistor_GetTempC(uint16_t adcValue)
{
    // 1) Convert ADC reading to voltage across thermistor
    float vTherm = (adcValue / ADC_MAX) * VREF;

    // 2) Compute thermistor resistance from divider: V = VREF * (Rtherm / (Rtherm + R_FIXED))
    float rTherm = R_FIXED * (VREF / vTherm - 1.0f);

    // 3) Apply B-parameter equation: 1/T = 1/T0 + (1/B) * ln(R/R0)
    float lnTerm = logf(rTherm / R0);
    float invT  = (1.0f / T0_KELVIN) + (lnTerm / B_COEF);

    // 4) Convert Kelvin back to °C
    float tempK = 1.0f / invT;
    float tempC = tempK - 273.15f;

    return tempC;
}

int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	Console_Init(115200);


	GPIO_Pin_Init(GPIOD, 12, GPIO_Configuration.Mode.General_Purpose_Output,
			GPIO_Configuration.Output_Type.Push_Pull,
			GPIO_Configuration.Speed.Very_High_Speed,
			GPIO_Configuration.Pull.Pull_Down,
			GPIO_Configuration.Alternate_Functions.None);

	GPIO_Pin_Init(GPIOD, 13, GPIO_Configuration.Mode.General_Purpose_Output,
			GPIO_Configuration.Output_Type.Push_Pull,
			GPIO_Configuration.Speed.Very_High_Speed,
			GPIO_Configuration.Pull.Pull_Down,
			GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(GPIOD, 14, GPIO_Configuration.Mode.General_Purpose_Output,
			GPIO_Configuration.Output_Type.Push_Pull,
			GPIO_Configuration.Speed.Very_High_Speed,
			GPIO_Configuration.Pull.Pull_Down,
			GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(GPIOD, 15, GPIO_Configuration.Mode.General_Purpose_Output,
			GPIO_Configuration.Output_Type.Push_Pull,
			GPIO_Configuration.Speed.Very_High_Speed,
			GPIO_Configuration.Pull.Pull_Down,
			GPIO_Configuration.Alternate_Functions.None);


	thermistor_config.Channel_0.Enable = ADC_Configuration.Channel.Enable.Enable;
	thermistor_config.Channel_0.Sample_Time = ADC_Configuration.Channel.Sample_Time._56_Cycles;
	thermistor_config.Channel_0.Sequence_Number = ADC_Configuration.Channel.Sequence_Number.Sequence_1;

	thermistor_config.Channel_1.Enable = ADC_Configuration.Channel.Enable.Enable;
	thermistor_config.Channel_1.Sample_Time = ADC_Configuration.Channel.Sample_Time._56_Cycles;
	thermistor_config.Channel_1.Sequence_Number = ADC_Configuration.Channel.Sequence_Number.Sequence_2;

	thermistor_config.Channel_2.Enable = ADC_Configuration.Channel.Enable.Enable;
	thermistor_config.Channel_2.Sample_Time = ADC_Configuration.Channel.Sample_Time._56_Cycles;
	thermistor_config.Channel_2.Sequence_Number = ADC_Configuration.Channel.Sequence_Number.Sequence_3;

	thermistor_config.Channel_3.Enable = ADC_Configuration.Channel.Enable.Enable;
	thermistor_config.Channel_3.Sample_Time = ADC_Configuration.Channel.Sample_Time._56_Cycles;
	thermistor_config.Channel_3.Sequence_Number = ADC_Configuration.Channel.Sequence_Number.Sequence_4;

	thermistor_config.Channel_4.Enable = ADC_Configuration.Channel.Enable.Enable;
	thermistor_config.Channel_4.Sample_Time = ADC_Configuration.Channel.Sample_Time._56_Cycles;
	thermistor_config.Channel_4.Sequence_Number = ADC_Configuration.Channel.Sequence_Number.Sequence_5;

	thermistor_config.Port = ADC_Configuration.Port._ADC1_;
	thermistor_config.Channel_Type = ADC_Configuration.Channel_Type.Regular;
	thermistor_config.Conversion_Mode = ADC_Configuration.Conversion_Mode.Single;
	thermistor_config.Data_Alignment = ADC_Configuration.Data_Alignment.Right_Justified;
	thermistor_config.Resolution = ADC_Configuration.Resolution.Bit_12;
	thermistor_config.Watchdog_Analog.Enable = ADC_Configuration._Watchdog_Analog_.Disable;
	thermistor_config.External_Trigger.Enable = ADC_Configuration.Regular_External_Trigger_Enable.Trigger_On_Rising_Edge;
	thermistor_config.External_Trigger.Sampling_Frequency = 100;
	thermistor_config.External_Trigger.Trigger_Event = ADC_Configuration.Regular_External_Trigger_Event.Timer_2_CC2;

	ADC_Init(&thermistor_config);
	ADC_Start_Capture(&thermistor_config, (uint16_t*)&thermistor_buffer);

	GPIO_Pin_Toggle(GPIOD, 12);
	GPIO_Pin_Toggle(GPIOD, 14);




	for(;;)
	{
		thermistor[0] = Thermistor_GetTempC(thermistor_buffer[0]);
		thermistor[1] = Thermistor_GetTempC(thermistor_buffer[1]);
		thermistor[2] = Thermistor_GetTempC(thermistor_buffer[2]);
		thermistor[3] = Thermistor_GetTempC(thermistor_buffer[3]);
		thermistor[4] = Thermistor_GetTempC(thermistor_buffer[4]);



		printConsole("%f, %f, %f, %f, %f \r\n",thermistor[0],thermistor[1],thermistor[2],thermistor[3],
				thermistor[4]);

		GPIO_Pin_Toggle(GPIOD, 12);
		GPIO_Pin_Toggle(GPIOD, 13);
		GPIO_Pin_Toggle(GPIOD, 14);
		GPIO_Pin_Toggle(GPIOD, 15);
		Delay_milli(100);
	}
}


